runtime: python312 
entrypoint: gunicorn -b :$PORT projetopw.wsgi  # Substitua "seu_projeto" pelo nome do seu projeto Django (o mesmo nome da pasta que tem o arquivo settings.py)

handlers:
- url: /static
  static_dir: static_gcloud/
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5
