# Generated by Django 4.2.20 on 2025-08-14 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campus",
            options={"ordering": []},
        ),
        migrations.AddField(
            model_name="campus",
            name="cadastrado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
