# Generated by Django 4.2.20 on 2025-05-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="senha",
        ),
        migrations.AddField(
            model_name="sugestao",
            name="anexos",
            field=models.FileField(blank=True, null=True, upload_to="anexos/"),
        ),
        migrations.AddField(
            model_name="sugestao",
            name="prioridade",
            field=models.CharField(
                blank=True,
                choices=[("baixa", "Baixa"), ("media", "Média"), ("alta", "Alta")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sugestao",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("analise", "Em análise"),
                    ("andamento", "Em andamento"),
                    ("concluida", "Concluída"),
                    ("rejeitada", "Rejeitada"),
                ],
                default="aberta",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="campus",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="paginas.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="sugestao",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="paginas.campus"
            ),
        ),
        migrations.RemoveField(
            model_name="sugestao",
            name="categorias",
        ),
        migrations.AlterField(
            model_name="sugestao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="paginas.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name="sugestao",
            name="categorias",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="paginas.categoria",
            ),
            preserve_default=False,
        ),
    ]
