# Generated by Django 4.2.20 on 2025-08-21 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paginas", "0002_alter_campus_options_campus_cadastrado_em"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campus",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="comentario",
            options={"ordering": ["-data_comentario"]},
        ),
        migrations.AlterModelOptions(
            name="curso",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="sugestao",
            options={"ordering": ["-data_criacao"]},
        ),
        migrations.AlterModelOptions(
            name="tiposolicitacao",
            options={"ordering": ["descricao"]},
        ),
        migrations.AlterField(
            model_name="sugestao",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="paginas.categoria"
            ),
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escolha", models.BooleanField()),
                (
                    "sugestao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="paginas.sugestao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("sugestao", "usuario")},
            },
        ),
    ]
