# Generated by Django 4.2.20 on 2025-08-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0003_alter_campus_options_alter_categoria_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="campus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="paginas.campus",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="nome",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
