# Generated by Django 4.2.20 on 2025-05-26 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paginas", "0003_perfil_rename_categorias_sugestao_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="paginas.campus"
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="sugestao",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="paginas.campus"
            ),
        ),
        migrations.AlterField(
            model_name="sugestao",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="paginas.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="sugestao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
